Exclude corrupted tables from columns/comments response
It has been observed that reading `table_comments` table may fail with
(stacktrace from `426-galaxy-1-u93-ge6f8fd31cd`):

```
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "metadataLocation" is null
	at io.trino.plugin.iceberg.catalog.glue.TrinoGlueCatalog.getTableComment(TrinoGlueCatalog.java:710)
	at io.trino.plugin.iceberg.IcebergMetadata.getTableComment(IcebergMetadata.java:340)
	at io.trino.plugin.objectstore.ObjectStoreMetadata.lambda$streamRelationComments$15(ObjectStoreMetadata.java:784)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at io.trino.plugin.objectstore.ObjectStoreMetadata.streamRelationComments(ObjectStoreMetadata.java:752)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.streamRelationComments(ClassLoaderSafeConnectorMetadata.java:348)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorMetadata.streamRelationComments(ClassLoaderSafeConnectorMetadata.java:99)
	at io.trino.tracing.TracingConnectorMetadata.streamRelationComments(TracingConnectorMetadata.java:320)
	at io.trino.metadata.MetadataManager.listRelationComments(MetadataManager.java:729)
```

This means that customer Glue catalog has a table that passes
`isIcebergTable(table)` check, but is not a valid Iceberg table, as it
lacks the `metadata_location` table property/parameter.