Revert "Remove usages of Hadoop Path for Hive LocationService"
This reverts commit 8bd9f754fb2aec61ffa353adfb421b460b60d947.

This commit breaks Hive tables when schema location contains double
slashes.
Before that commit, table location would be normalized.
After that commit, table location was normalized, but writes to such
tables weren't handled correctly, producing broken file names that
cannot be read later

```
java.lang.IllegalArgumentException: Fragment is not allowed in a file system location: s3://galaxy-trino-ci/static_test_resources/test_double_slashes/hive_417_ctas/20230526_115536_27891_q8qvz_3e6ef121-c5ba-4130-bf9b-3b0ec798afcf#%2Fstatic_test_resources%2F%2Ftest_double_slashes%2Fhive_417_ctas%2F20230526_115536_27891_q8qvz_3e6ef121-c5ba-4130-bf9b-3b0ec798afcf
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:220)
	at io.trino.filesystem.Location.of(Location.java:65)
	at io.trino.plugin.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:159)
	at com.starburstdata.trino.plugins.dynamicfiltering.DynamicRowFilteringPageSourceProvider.createPageSource(DynamicRowFilteringPageSourceProvider.java:54)
	at io.trino.plugin.base.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:49)
	at io.trino.plugin.objectstore.ObjectStorePageSourceProvider.createPageSource(ObjectStorePageSourceProvider.java:62)
	at io.trino.split.PageSourceManager.createPageSource(PageSourceManager.java:62)
	at io.trino.operator.TableScanOperator.getOutput(TableScanOperator.java:298)
	at io.trino.operator.Driver.processInternal(Driver.java:402)
	at io.trino.operator.Driver.lambda$process$8(Driver.java:305)
	at io.trino.operator.Driver.tryWithLock(Driver.java:701)
	at io.trino.operator.Driver.process(Driver.java:297)
	at io.trino.operator.Driver.processForDuration(Driver.java:268)
	at io.trino.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:888)
	at io.trino.execution.executor.PrioritizedSplitRunner.process(PrioritizedSplitRunner.java:187)
	at io.trino.execution.executor.TaskExecutor$TaskRunner.run(TaskExecutor.java:561)
	at io.trino.$gen.Trino_417_galaxy_1_u30_gc770fc560a____20230526_115229_2.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```