Allow to drop tables in Oracle tests
This fix the failure in:
testDynamicFilteringDomainCompactionThreshold(com.starburstdata.presto.plugin.oracle.TestOracleDynamicFiltering)
which fails with:
java.lang.RuntimeException: DROP TABLE is disabled in this catalog

(cherry-picked from commit: f56c6b011e78e836c1da8d72aa6f153af109abbf)

(cherry picked from commit 488a462bdd8e4b0c5dec7ffc05051a6b6d7b5e97)